# Generated by Django 4.0.3 on 2022-05-27 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('nacimiento', models.DateField()),
                ('biografia', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('nacimiento', models.DateField()),
                ('biografia', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('resumen', models.CharField(max_length=300)),
                ('lanzamiento', models.DateField()),
                ('actores', models.ManyToManyField(to='App_peliculas.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='App_peliculas.director')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(max_length=254)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resenia', models.CharField(max_length=400)),
                ('resenia_aprobada', models.BooleanField(default=False)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_peliculas.pelicula')),
            ],
        ),
    ]
