# Generated by Django 4.0.3 on 2022-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0002_pelicula_puntaje_alter_critica_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='actores/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='directores/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/'),
        ),
    ]
