# Generated by Django 4.0.3 on 2022-06-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0003_alter_actor_foto_alter_director_foto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
