# Generated by Django 4.0.3 on 2022-06-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0004_delete_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cant_criticas',
            field=models.IntegerField(default=0),
        ),
    ]
