# Generated by Django 4.0.3 on 2022-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0005_pelicula_cant_criticas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='resenia',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
