# Generated by Django 4.0.3 on 2022-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0006_alter_critica_resenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nacimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='nacimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='lanzamiento',
            field=models.IntegerField(),
        ),
    ]
