# Generated by Django 4.0.3 on 2022-06-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0007_alter_actor_nacimiento_alter_director_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critica',
            name='resenia_aprobada',
        ),
        migrations.AddField(
            model_name='critica',
            name='estado_resenia',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=9),
        ),
        migrations.AlterField(
            model_name='actor',
            name='foto',
            field=models.ImageField(blank=True, default='iconos/default_profile.png', null=True, upload_to='actores/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, default='iconos/default_profile.png', null=True, upload_to='directores/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, default='iconos/default_film.png', null=True, upload_to='peliculas/'),
        ),
    ]
