# Generated by Django 4.0.3 on 2022-07-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0009_alter_actor_options_alter_critica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='biografia',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='director',
            name='biografia',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(max_length=300),
        ),
    ]
